# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-07 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('body_type', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('transmission', models.CharField(choices=[('AUTO', 'automatic'), ('MANUAL', 'manual')], max_length=256)),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('series', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('seats', models.IntegerField(blank=True, default=None, null=True)),
                ('colour', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('registration_number', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('D', 'Diesel'), ('P', 'Petrol')], default=None, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarOwnerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(blank=True, default=None, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carowner.CarOwnerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carcomment', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carowner.CarOwnerProfile')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carowner.CarOwnerProfile'),
        ),
    ]
